# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  dev-run-ngrok:
    desc: Start the database and backend services enabled for ngrok integration
    cmds:
      - docker compose -f compose-ngrok.yaml up -d ledger_db
      - docker compose -f compose-ngrok.yaml up -d ledger_backend

  dev-down-ngrok:
    desc: Stop the services
    cmd: docker compose -f compose-ngrok.yaml down

  dev-logs-ngrok:
    desc: Print logs for the running services
    cmd: docker compose -f compose-ngrok.yaml logs
